# Generated by Django 4.1.7 on 2023-07-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0004_alter_player_mesh'),
        ('digg', '0003_alter_block_mesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=16)),
                ('size_x', models.BigIntegerField()),
                ('size_y', models.BigIntegerField()),
                ('size_z', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digg.block')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
