# Generated by Django 4.1.5 on 2023-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mesh', models.CharField(max_length=65536)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
