# Generated by Django 4.1.7 on 2023-07-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_player_mesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mesh',
            field=models.TextField(default='v 0 0 0\nv 0 0 1\nv 0 1 0\nv 0 1 1\nv 1 0 0\nv 1 0 1\nv 1 1 0\nv 1 1 1\n\nvn 1 0 0\nvn -1 0 0\nvn 0 1 0\nvn 0 -1 0\nvn 0 0 1\nvn 0 0 -1\n\nf 1//2 2 3//2\nf 2 4//2 3//2\nf 2//5 6//5 4//5\nf 4//5 6//5 8//5\nf 1//4 5//4 2//4\nf 2//4 5//4 6//4\nf 3 8//3 7//3\nf 3 4//3 8//3\nf 1//6 3//6 7//6\nf 1//6 7//6 5//6\nf 5//1 8//1 6//1\nf 5//1 7//1 8//1\n'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='0,0,0', max_length=100),
        ),
    ]
