# Generated by Django 4.1.6 on 2024-01-24 18:47

import math
from django.db import migrations, models


def forwards(apps, schema_editor):
    """
    Update level for each player to match the scale of their mesh.
    """
    Player = apps.get_model("player", "player")
    for player in Player.objects.all():
        player.level = int(
            0.5 + math.log2(1 / float(player.mesh.split("v ")[8].split(" ")[0]) * 8)
        )
        player.save()


def backwards(apps, schema_editor):
    """
    Update level for each player to match the scale of their mesh.
    """
    Player = apps.get_model("player", "player")
    for player in Player.objects.all():
        s = 8 / 2**player.level
        player.mesh = f"""v 0 0 0
v 0 0 {s}
v 0 {s} 0
v 0 {s} {s}
v {s} 0 0
v {s} 0 {s}
v {s} {s} 0
v {s} {s} {s}

vn 1 0 0
vn -1 0 0
vn 0 1 0
vn 0 -1 0
vn 0 0 1
vn 0 0 -1

f 1//2 2 3//2
f 2 4//2 3//2
f 2//5 6//5 4//5
f 4//5 6//5 8//5
f 1//4 5//4 2//4
f 2//4 5//4 6//4
f 3 8//3 7//3
f 3 4//3 8//3
f 1//6 3//6 7//6
f 1//6 7//6 5//6
f 5//1 8//1 6//1
f 5//1 7//1 8//1
"""
        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0005_alter_player_mesh_alter_player_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="level",
            field=models.BigIntegerField(default=3),
        ),
        migrations.RunPython(forwards, backwards, atomic=True),
        migrations.RemoveField(
            model_name="player",
            name="mesh",
        ),
    ]
