# Generated by Django 4.1.5 on 2023-01-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('mesh', models.CharField(max_length=16777216)),
                ('position', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mesh', models.CharField(max_length=65536)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformQueue',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='digg.player')),
                ('position', models.CharField(max_length=16)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digg.block')),
            ],
        ),
        migrations.CreateModel(
            name='Terraformer',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='digg.player')),
                ('position', models.CharField(max_length=16)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='digg.block')),
            ],
        ),
    ]
