# Generated by Django 4.1.5 on 2023-01-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('digg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformer',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='player.player'),
        ),
        migrations.AlterField(
            model_name='terraformqueue',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='player.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
