# Generated by Django 4.1.6 on 2023-02-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digg', '0002_alter_terraformer_player_alter_terraformqueue_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='mesh',
            field=models.TextField(),
        ),
    ]
